#!/usr/bin/env php
<?php declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

$config = require __DIR__ . '/configs/common.php';
$app = new \Symfony\Component\Console\Application('PHP tech stats', '1.0');
$app->addCommands([
    new \app\commands\GetStats($config),
    new \app\commands\GenCharts($config),
]);
$app->run();