<?php

return [
    'PHP frameworks' => [
        'Zend Framework' => '\szf(\s|\d)|zend',
        'Symfony' => 'symfony|symphony',
        'Yii' => 'yii',
        'CakePHP' => 'cake\s*php',
        'Laravel' => 'laravel',
        'CodeIgniter' => 'code\s*igniter',
        'Kohana' => 'kohana',
        'Phalcon' => 'phalcon',
        'Zephir' => 'zephir',
        'Aura' => 'aura',
        'Silex' => 'silex',
        'FuelPHP' => 'fuel',
        'Slim' => 'slim',
        'PHPixie' => 'phpixie',
        'Fat-Free' => 'fat\s*free',
        'Lumen' => 'lumen',
        'Lithium (li3)' => 'li3|lithium',
    ],

    'PHP CMS' => [
        'Drupal' => 'drupal',
        'Wordpress' => 'wordpress|\swp\s',
        'Typo' => 'typo\d',
        'Terminal4' => 'terminal\s*\d',
        'Joomla' => 'joomla',
        'Magento' => 'magento',
        'Bitrix' => 'bitrix',
        'OpenCart' => 'open\s*cart',
        'MODX' => 'mod\s*x',
        'NetCat' => 'net\s*cat',
        'DataLife Engine' => 'data\s*life',
        'UMI.CMS' => 'umi',
    ],

    'PHP форумы' => [
        'phpBB' => 'php\s*bb',
        'SMF' => 'smf',
        'Vbulletin' => 'v\s*bulletin',
        'IPS' => 'ips',
        'PunBB' => 'pun\s*bb',
        'Vanilla' => 'vanilla',
        'Xenforo' => 'xenforo',
        'ExBB' => 'ex\s*bb',
        'FluxBB' =>'flux\s*bb',
        'Flarum' => 'flarum',
    ],

    'PHP шаблонизаторы' => [
        'Smarty' => 'smarty',
        'Twig' => 'twig',
        'Volt' => 'volt',
        'Blade' => 'blade',
    ],

    'Frontend' => [
        'jQuery' => 'j\s*query',
        'Bootstrap' => 'bootstrap',
        'Angular' => 'angular',
        'Bower' => 'bower',
        'TypeScript' => 'type\s*script',
        'LESS' => 'less',
        'SASS' => 'sass',
        'Gulp' => 'gulp',
        'Grunt' => 'grunt',
        'Yeoman' => 'yeoman',
        'Knockout' => 'knockout',
        'Backbone' => 'backbone',
        'Marionette.js' => 'marionette',
        'Ember' => 'ember',
        'io.js' => 'io\.js',
        'SockJS' => 'sock\s*js',
        'Underscore' => 'underscore',
        'ReactJS' => 'react\s*js',
        'ExtJS' => 'ext\s*js',
        'ECMAScript' => 'ecma\s*script',
        'Dojo' => 'dojo',
        'Meteor.js' => 'meteor',
        'Jade' => 'jade',
        'Stylus' => 'stylus',
        'PostCSS' => 'postcss',
        'БЭМ' => 'бэм|bem',
        'RequireJS' => 'require\s*js',
        'CoffeeScript' => 'coffee\s*script',
        'Webpack' => 'web\s*pack',
        'Comet' => 'comet',
        'WebRTC' => 'web\s*rtc',
    ],

    'Databases' => [
        'MySQL' => 'mysql',
        'PostgreSQL' => 'postgre',
        'SQLite' => 'sql\s*lite',
        'MSSQL' => 'ms\s*sql',
        'MongoDB' => 'mongo',
        'Redis' => 'redis',
        'MariaDB' => 'maria\s*db',
        'Tarantool' => 'tarantool',
        'ElasticSearch' => 'elastic\s*search',
        'Cassandra' => 'cassandra',
        'Oracle' => 'oracle',
        'RethinkDB' => 'rethink\s*db',
        'CouchDB' => 'couch\s*db',
        'Riak' => 'riak',
        'HBase' => 'hbase',
    ],

    'Очереди' => [
        'RabbitMQ' => 'rabbit\s*mq',
        'AMQP' => 'amqp',
        'ActiveMQ' => 'active\s*mq',
        'Beanstalk' => 'beanstalk',
        'Gearman' => 'gearman',
    ],

    'Поисковые движки' => [
        'Coveo' => 'coveo',
        'Sphinx' => 'sphinx',
        'Lucene' => 'lucene',
        'Solr' => 'solr',
    ],

    'VCS' => [
        'Mercurial' => 'mercurial|\shg\s',
        'Git' => 'git',
        'Subversion' => 'subversion|svn'
    ],

    'Web-сервера' => [
        'Apache' => 'apache',
        'NGINX' => 'nginx',
        'IIS' => 'iis',
        'lighttpd' => 'lighttpd|light\s*http',
    ],

    'Виртуализация' => [
        'Docker' => 'docker',
        'Puppet' => 'puppet',
        'Vagrant' => 'vagrant',
        'OpenVZ' => 'open.*vz',
        'VirtualBox' => 'virtual.*box',
        'VMware' => 'vm.*ware',
        'Parallels Desktop' => 'parallels',
    ],

    'Логирование и мониторинг' => [
        'Munin' => 'munin',
        'Graylog' => 'gray.*log',
        'Grafana' => 'grafana',
        'Logstash' => 'log.*stash',
        'logrotate' => 'logrotate',
        'Cacti' => 'cacti|cacty',
    ],

    'Кеширование' => [
        'APC' => 'apc',
        'XCache' => 'xcache',
        'Varnish' => 'varnish',
        'Memcache' => 'memcache',
    ],

    'Профилирование и отладка' => [
        'XHprof' => 'xhprof',
        'Xdebug' => 'xdebug',
        'DBG' => 'dbg',
        'ZendDebug' => 'zend.*debug',
        'Memtrack' => 'memtrack',
        'Pinba' => 'pinba',
    ],

    'Техники разработки' => [
        'DDD' => 'ddd',
        'TDD' => 'tdd',
        'BDD' => 'bdd',
    ],

    'Прочее' => [
        'LAMP' => 'lamp',
        'WAMP' => 'wamp',
        'XAMPP' => 'xampp',
        'Bash' => 'bash|shh|shell',
        'Linux' => 'linux',
        'Unix' => 'unix',
        'XML' => 'xml',
        'SOAP' => 'soap',
        'REST' => 'rest',
        'Doctrine' => 'doctrine',
        'Composer' => 'composer',
        'RegExp' => 'regexp',
        'ООП' => 'oop|ооп|object orientated',
        'MVC' => 'mvc',
        'PSR' => 'psr',
        'SPL' => 'spl',
        'SOLID' => 'solid',
        'HHVM' => 'hhvm',
    ],

    'CI' => [
        'Bamboo' => 'bamboo',
        'Stash' => 'stash',
        'TeamCity' => 'team\s*city',
        'Jenkins' => 'jenkins',
        'Phing' => 'phing',
        'Travis' => 'travis',
        'Capistrano' => 'capistrano',
    ],

    'Issue trackers' => [
        'JIRA' => 'jira',
        'Confluence' => 'confluence',
        'Redmine' => 'redmine',
        'Mantis' => 'mantis',
        'Bugzilla' => 'bugzilla',
        'Youtrack' => 'youtrack'
    ],

    'IDE' => [
        'PHPStorm' => 'php\s*storm',
        'NetBeans' => 'net\s*beans',
        'Eclipse' => 'eclipse',
        'Aptana' => 'aptana',
        'PHPDesigner' => 'php\s*designer',
        'SublimeText' => 'sublime',
        'Vim' => 'vim',
        'ZendStudio' => 'zend\s*studio',
        'Dreamweaver' => 'dream\s*weaver',
        'Komodo' => 'komodo',
    ],

    'Тестирование' => [
        'Selenium' => 'selenium|селениум',
        'PHP Unit' => 'php\s*unit',
        'Codeception' => 'code\s*ception',
    ],

    'Должность' => [
        'Юниор' => 'junior|юниор|начинающий',
        'Мидл' => 'middle|мидл|средний',
        'Сеньер' => 'senior|сеньер|сеньёр|мастер',
        'Техлид' => 'тех.*лид|tech.*lead',
        'Тимлид' => 'тим.*лид|teem.*lead',
    ],

    'Методологии разработки' => [
        'Agile' => 'agile',
        'Scrum' => 'scrum',
        'Kanban' => 'kanban',
    ],
];